#!/usr/bin/env bash

set +x
# args:
# 1: input folder where the photos are (must exist!)
# 2: name of output folder (will be created)

appname="autocrop"

if [ "$#" -lt 2 ]; then
	echo "-$appname: 2 arguments requested"
	exit 1
fi

# etape 1: lecture des parametres

src_dir=$1
dst_dir=$2

if [ "$1" = "-m" ]
then
	modemanual=$1
	src_dir=$2
	if [ "$#" -lt 3 ]; then
		echo "-$appname: missing destination folder, exiting..."
		exit 1
	fi
	dst_dir=$3
fi

# remove potential trailing slashes
ddir=${dst_dir%/}
sdir=${src_dir%/}


if [ "$ddir" = "$sdir" ]
then
	echo "-$appname: error, source and destination folder cannot be the same"
	exit 2
fi


mkdir -p "$ddir"

for fn in $sdir/*
do
	echo "-$appname: processing file $fn"
	./autocrop2.py $modemanual "$fn" "$ddir" 
#	trombino_autocrop_gui.py $modemanual "$fn" "$ddir" 
	errval=$?
	if ! [ $errval = 0 ]
	then
		echo "-$appname: failure, cropping app returned $errval, stopping"
		exit 1
	fi
done

