#!/usr/bin/env bash

set +x
# args:
# 1: input folder where the photos are (must exist!)
# 2: name of output folder (will be created)


if [ "$#" -lt 2 ]; then
	echo "-autocrop: 2 arguments requested"
	exit 1
fi

# etape 1: lecture des parametres

src_dir=$1
dst_dir=$2

if [ "$1" = "-m" ]
then
	modemanual=$1
	src_dir=$2
	if [ "$#" -lt 3 ]; then
		echo "-autocrop: missing destination folder, exiting..."
		exit 1
	fi
	dst_dir=$3
fi


mkdir -p "$dst_dir"

for fn in $src_dir/*
do
	echo "-autocrop: processing file $fn"
	trombino_autocrop_gui.py $modemanual "$fn" "$dst_dir" 
	errval=$?
	if ! [ $errval = 0 ]
	then
		echo "-autocrop: failure, cropping app returned $errval, stopping"
		exit 1
	fi
done

