#!/bin/bash
set +x

# !!!!!!!!!!!!!!!! WIP !!!!!!!!!!!!!!!!

# bphoto - Batch process Photos
# a wrapper over Imagemagick to process a set of photos with basic adjustements:
# convert to B&W, reduce size, brightness and contrast

function usage
{
echo " args:"
echo " -1: input folder"
echo " -2: output folder (will be created)"
echo " -3: command: one of these:"
echo "  - R: reduce size, requires a 4th arg: reducing amount (%)"
echo "   (value '50' will produce an image half the orignal size)"
echo "  - W: convert to B&W"
echo "  - B: brightness and contrast (2 more values needed)"

echo " Examples:"
echo " $ bphoto src dst R 20"
echo " $ bphoto src dst W"
echo " $ bphoto src dst B 50 10"
}

#========================================
function resize
{
	mkdir -p $2
	rm $2/*
	for file in $1/*; do
		echo "processing file $file"
		convert $file -resize $3% $2/`basename $file`;
	done
}


function bright
{
	mkdir -p $2
	rm $2/*
	for file in $1/*; do
		echo "processing file $file"	
		convert $file -brightness-contrast $3x$4 $2/`basename $file`;
	done
}

function bw
{
	mkdir -p $2
	rm $2/*

	for file in $1/*; do
		echo "processing file $file"
		convert $file -set colorspace Gray -separate -average $2/`basename $file`;
	done
}


#========================================
# START

which convert >/dev/null
isAvailable=$?
if ! [ $isAvailable = 0 ]
then
	echo "Error, program 'convert' is not available in the path, ImageMagick is required"
	exit 2
fi

if [ "$#" -lt 3 ]; then
	echo " -3 arguments mininum"
	usage
	exit 1
fi

srcd=$1
dstd=$2
cmd=$3


# remove potential trailing slashes
src=${srcd%/}
dst=${dstd%/}


if [ "$src" = "$dst" ]
then
	echo " -Error, source and destination floder cant be the same"
	exit 2
fi


while [ -n "$3" ]; do # while loop starts
	case "$3" in
	R)
		echo "R"
		if [ "$#" -lt 4 ];
		then
			echo " -command 'R': requires a reduction rate"
		else
			resize $src $dst $4
			exit 0
		fi
		shift
		;;
	W)
		echo "W"
		bw $src $dst
		exit 0
		shift
		;;
	B)
		echo "B"
		if [ "$#" -lt 5 ];
		then
			echo "nb=$#"
			echo " -command 'B' requires resize brightness and contrast values"
		else
			bright $src $dst $4 $5
			exit 0
		fi
		shift
		;;
	*) echo " -Error: invalid command $3"; usage; exit 1 ;;
	esac
	shift
done


