#!/usr/bin/env bash

# S. Kramm - 2022-2023
# https://github.com/skramm/trombino
# création automatique de trombinoscope

version=1.3.0
# 2024-09-20: ajout version HTML (switch -w) et ajout taille des groupes


set +x

# dossier par défaut contenant les photos
photos=photos/

# fichier csv d'entrée par défaut contenant groupe,nom,prénom
input_file=liste.csv

# nom fichier de sortie par défaut
out_fn=trombi

# nb de colonnes par défaut
nb_cols=4

# nb de lignes max
max_lines=4

# initialisation variables
count_lines=0
count_cols=0
count_pages=0

# default field separator
IFS=,
fsep=,

# swap Firstname-Lastname
swapfnln=false

current_group=nogroup
header_file=trombi_header.tex

# output format
html=0
latex=1

#-----------------------------------------------------------------------------
# FONCTIONS

#-----------------------------------------------------------------------------
# A CLEANER!!!
function close_line
{
#	echo "F: close_line count_cols=$count_cols"

	if [ $latex = 1 ]
	then
		(( count_cols+=1 ))
		while [ $count_cols -lt $nb_cols ]
		do
			echo "&" >>$outfile_tex
			(( count_cols+=1 ))
		done
		echo "\\\ \hline" >>$outfile_tex
	fi

	if [ $html = 1 ]
	then
		while [ $count_cols -lt $nb_cols ]
		do
			echo "<td></td>" >>$outfile_html
			(( count_cols+=1 ))
		done
		echo "</tr>" >> $outfile_html
		line_is_closed=true
	fi

	count_cols=0
}
#-----------------------------------------------------------------------------
# Adds missing cells to the current table (latex AND html) and closes the table
function close_page
{
#	echo "F: close_page count_cols=$count_cols"
	if $table_is_closed
	then
		return;
	fi

	if ! $line_is_closed ;
	then
		close_line
	fi

	if [ $html = 1 ]
	then
		echo "</table>" >> $outfile_html
	fi

	if [ $latex = 1 ]
	then
		echo "\end{tabularx}" >>$outfile_tex
		echo "\clearpage" >>$outfile_tex
	fi

	line_is_closed=true
	table_is_closed=true;
}

#-----------------------------------------------------
function reset_all
{
	count_lines=0
	count_cols=0
#	current_group=nogroup
}

#-----------------------------------------------------
# opens new page
# - arg1: 0: no group title, 1: print group as title
# - arg2: group
function new_page
{
#	echo "F: new_page"
	if [ $html = 1 ]
	then
		if [ $1 = 1 ];
		then
			echo -e "<h3>Groupe $2: ${groupsize[$2]}</h3>\n<table>" >>$outfile_html
		fi
	fi

	if [ $latex = 1 ]
	then
		if [ $1 = 1 ]
		then
			echo "\begin{center}" >>$outfile_tex
			echo "\bf \huge" >>$outfile_tex
			echo "Groupe $2: ${groupsize[$2]}" >>$outfile_tex
			echo "\end{center}" >>$outfile_tex
		fi
		echo "" >>$outfile_tex
		echo -n "\begin{tabularx}{\linewidth}{|" >>$outfile_tex
		for (( i=0;i<$nb_cols;i++ ))
		do
			printf "X|" >>$outfile_tex
		done
		echo "}" >>$outfile_tex
		echo "\hline" >>$outfile_tex
	fi
	table_is_closed=false;
}


#-------------------- Main function for global output file, process one line -------------------------
function process_line_all
{
	line_is_closed=false

	if [ "$count_cols" -eq "0" ]
	then
		if [ "$count_lines" -eq "0" ]
		then
			new_page 0
		fi
		if [ $html = 1 ]
		then
			echo "<tr>" >> $outfile_html
		fi
	fi

	photo="${1%.*}"
	photoh=$1
	firstname=$4
	lastname=$3
	current_group=$2

	if [ $latex = 1 ]
	then
		echo "\includegraphics[width=$width\textwidth]{$photo} \newline" >>$outfile_tex
		echo "$firstname $lastname \newline gr $current_group">>$outfile_tex
		if [ $debug_mode = true ]
		then
			echo "- $photoh" >>$outfile_tex
		fi
	fi
	if [ $html = 1 ]
	then
		echo "<td><img src='$photos$photoh'>" >>$outfile_html
		echo "<p>$firstname $lastname <br> $current_group">>$outfile_html
		if [ $debug_mode = true ]
		then
			echo "- $photoh" >>$outfile_html
		fi
		echo "</p></td>">>$outfile_html
	fi

	(( count_cols += 1 ))

	if [ "$count_cols" -eq "$nb_cols" ]
	then
		if [ $latex = 1 ]
		then
			echo "\\\ \hline" >>$outfile_tex
		fi
		if [ $html = 1 ]
		then
			echo "</tr>" >>$outfile_html
		fi

		line_is_closed=true
		(( count_lines += 1 ))
		count_cols=0

		if [ $latex = 1 ]
		then
			if [ $count_lines -eq $max_lines ]
			then
				echo "\end{tabularx}" >>$outfile_tex
				echo "\clearpage" >>$outfile_tex
				count_lines=0
			fi
		fi
	else
		if [ $latex = 1 ]
		then
			echo "&" >>$outfile_tex
		fi
	fi
}

# -----------------------------
function countgr
{
	if [ "$current_group" = "$2" ]
	then
		(( current_size+=1 ))
	else
		if [ "$current_group" = "nogroup" ]
		then
			current_group=$2
		else
			groupsize[$current_group]=$current_size
			current_group=$2
			current_size=1
		fi
	fi
}
# -----------------------------
# Count group size
# arg: file name
function countgrsize
{
	current_size=1
	current_group=nogroup
	while read line ; do
		countgr $line
	done < $1
	groupsize[$current_group]=$current_size
}

#-------------------- Main function for groups, process one line -------------------------
function process_line
{
# args: 1: photo filename, 2: group, 3: name, 4: firstname
#	echo "* processing name=$4 $3 current_group=$current_group  photo=$1 count_cols=$count_cols count_lines=$count_lines"

# SI nouveau groupe, alors il faut fermer la page et faire une nouvelle
	if [ "$current_group" != "$2" ]
	then
		if [ "$current_group" != "nogroup" ]
		then
			close_page
		fi
		current_group=$2
		reset_all
	fi

	if [ $count_cols = 0 ]
	then
		if [ $count_lines = 0 ]
		then
			new_page 1 $2
		fi
		if [ $html = 1 ]
		then
			echo "<tr>" >>$outfile_html
		fi
		((count_lines+=1))
	fi

	line_is_closed=false

	photo="${1%.*}"
	photoh=$1

	firstname=$4
	lastname=$3

	if [ $swapfnln = true ]; then
		tmpvar="$firstname"
		firstname="$lastname"
		lastname="$tmpvar"
	fi

# capitalize Lastname
	LN=$(echo "$lastname" | tr [:lower:] [:upper:])

# firstname is lower case, but first letter is uppercase
	firstname1=${firstname,,}
	firstname2=${firstname1^}

	if [ $latex = 1 ]
	then
		echo "\includegraphics[width=$width\textwidth]{$photo} \newline" >>$outfile_tex
		echo "$LN $firstname2" >>$outfile_tex
	fi
	if [ $html = 1 ]
	then
		echo "<td><img src='$photos$photoh'><br>" >>$outfile_html
		echo "<p>$LN $firstname2" >>$outfile_html
	fi

# print photo filename in debug mode
	if [ $debug_mode = true ];
	then
		if [ $latex = 1 ]
		then
			echo " - $photo" >>$outfile_tex
		fi
		if [ $html = 1 ]
		then
			echo " - $photoh" >>$outfile_html
		fi
	fi
	if [ $html = 1 ]
	then
		echo "</p></td>" >>$outfile_html
	fi

	(( count_cols += 1 ))

# if reached max number of columns
	if [ $count_cols = $nb_cols ];
	then
		close_line
	else
		if [ $latex = 1 ]
		then
			echo "&" >>$outfile_tex
		fi
	fi
}
#		echo "\\\ \hline" >>$outfile_tex
#		line_is_closed=true
#		(( count_lines += 1 ))
#		count_cols=0
#		if [ $html = 1 ]
#		then
#			echo "</td></tr>" >>$outfile_html
#		fi
#	else
#		if [ $latex = 1 ]
#		then
#			echo "&" >>$outfile_tex
#		fi
#		if [ $html = 1 ]
#		then
#			echo "</td>" >>$outfile_html
#		fi
#	fi

#	echo "count_cols=$count_cols count_lines =$count_lines  count_pages=$count_pages"
#}


# ----------------------------------------------------------------------------
function close_source
{
# close what might need to be closed
#	echo "F: close_source"

	if [ $count_cols = 0 ]
	then
		close_page
	fi

	if ! $table_is_closed ; then
		close_page
	fi

	if [ $latex = 1 ]
	then
		echo "\end{document}" >>$outfile_tex
	fi
}

# ----------------------------------------------------------------------------
# arg1: 0: trombi global; 1: trombi par groupe
function process_header
{
if [ $html = 1 ]
then
	echo "<!DOCTYPE html>" >$outfile_html
	echo -e "<head>\n<link rel='stylesheet' href='trombi.css'>" >>$outfile_html
	echo "<meta charset='utf-8'>" >>$outfile_html
	echo -n "<title>Trombinoscope " >>$outfile_html
	if [ $1 = 0 ]
	then
		echo -n "global" >>$outfile_html
	else
		echo -n "par groupe" >>$outfile_html
	fi
	echo -en "</title>\n</head>\n<body>\n<h1>Trombinoscope" >>$outfile_html
	if [ $1 = 0 ]
	then
		echo -e " global</h1>\n<table>" >>$outfile_html
	else
		echo " par groupe</h1>" >>$outfile_html
	fi
fi

if [ $latex = 1 ]
then
	cat $header_file >$outfile_tex

	echo "\lhead{" >>$outfile_tex
	if [ -f head_left.txt ]; then
		cat head_left.txt >>$outfile_tex
	else
		echo " -Warning: fichier head_left.txt absent"
	fi
	echo "}">>$outfile_tex

	echo "\chead{" >>$outfile_tex
	if [ -f head_center.txt ]; then
		cat head_center.txt >>$outfile_tex
	else
		echo " -Warning: fichier head_center.txt absent"
		if [ $1 = 0 ]
		then
			echo "Trombinoscope général" >>$outfile_tex
		else
			echo "Trombinoscope par groupe" >>$outfile_tex
		fi
	fi
	echo "}">>$outfile_tex

	echo "\rhead{">>$outfile_tex
	if [ -f head_right.txt ]; then
		cat head_right.txt >>$outfile_tex
	else
		echo " -Warning: fichier head_right.txt absent"
		echo "$(date +'%Y')" >>$outfile_tex
	fi
	echo "}">>$outfile_tex

	echo "\begin{document}\noindent">>$outfile_tex
	echo "\graphicspath{ {../$photos/} }">>$outfile_tex
fi
}

# ----------------------------------------------------------------------------
function latex_build
{
	cd BUILD
	echo "* Etape 2: démarrage pdflatex, fichier $outfile_tex"
	pdflatex -interaction=batchmode $outfile_tex 1>pdflatex.stdout 2>pdflatex.stderr
	if [ $? != 0 ]; then
		echo " -Erreur de compilation, voir fichier log"
	else
		echo " -Compilation: ok"
	fi

	if [ -f $outfile_tex.pdf ]; then
		echo " -Fichier $outfile_tex.pdf généré"
		mv $outfile_tex.pdf ..
	else
		echo " -Erreur fatale, pas de pdf généré"
	fi
	cd ..
}

# ----------------------------------------------------------------------------
# DEBUT SCRIPT

echo "trombino $version, https://github.com/skramm/trombino"
echo " -h pour les options"

debug_mode=false

# etape 1: lecture des parametres

while [ -n "$1" ]; do # while loop starts
	case "$1" in
	-l)
		input_file="$2"
		shift
		;;
	-p)
		photos="$2"
		shift
		;;
	-d)
		debug_mode=true
		;;
	-c)
		nb_cols="$2"
		shift
		;;
	-f)
		IFS=$2
		fsep=$2
		echo "Utilisation de '$IFS' -- '$fsep' comme séparateur"
		shift
		;;
	-o)
		out_fn="$2"
		shift
		;;
	-s)
		swapfnln=true
		;;
	-w)
		html=1
		;;
	-x)
		latex=0
		;;
	-h)
		echo " -l nom_fichier: pour spécifier un autre nom du fichier contenant la liste"
		echo " -p dossier: pour indiquer un autre dossier pour les photos"
		echo " -o nom_fichier: pour spécifier le nom du fichier pdf généré (sans extension!)"
		echo " -c: pour spécifier le nombre de colonnes"
		echo " -s: permutte nom - prénom"
		echo " -f SEP: separateur de champ"
		echo " -w: génération HTML"
		echo " -x: suppression génération pdf"
		echo " -d: active le mode \"debug\" qui va imprimer le nom de fichier de la photo avec le nom"
		exit 0
		;;

	*) echo " -Erreur: option $1 inconnue"; exit 1 ;;
	esac
	shift
done

if [ $html = 0 ] && [ $latex = 0 ]
then
	echo "Format de sortie: ni HTML ni pdf de sélectionné! (voir -h)"
	exit 0
fi

# création dossier temporaire
mkdir -p BUILD
#echo "input_file=$input_file"
#set -x
if [ -f $input_file ]; then
	echo " -Lecture liste dans fichier '$input_file'"
else
	echo " -Erreur: fichier '$input_file' introuvable!"
	exit 2
fi

if [ -d $photos ]; then
	echo " -Lecture des photos dans dossier '$photos'"
else
	echo " -Erreur: dossier '$photos' introuvable!"
	exit 3
fi

if [ $nb_cols -lt 2 ]
then
	echo "Erreur: minimum 2 colonnes"
	exit 3
fi

echo " -Nom du fichier de sortie: ${out_fn}"
outfile1=BUILD/${out_fn}_groupes.tex
outfile2=BUILD/${out_fn}_global.tex
outfile1_html=BUILD/${out_fn}_groupes.html
outfile2_html=BUILD/${out_fn}_global.html

echo " -Nbe colonnes par page=$nb_cols"

# calcul largeur cellule en fonction du nbe de colonnes
width=$(bc <<< "scale=2;0.85/$nb_cols")

# part 1: création du fichier contenant les paires photo - Id

# liste des photos
ls $photos -1 > BUILD/list_photos.txt

# check
sed '/^[[:space:]]*$/d' $input_file > BUILD/input.csv
n1=$(wc -l <BUILD/input.csv)
n2=$(wc -l <BUILD/list_photos.txt)
if [ $n1 != $n2 ]
then
	echo " -Erreur, $n2 photos et $n1 noms dans la liste!"
	exit 1
fi
echo " -Lecture de $n1 personnes & photos"

echo "* Etape 1: génération fichiers intermédiaires"

# merge photos + noms/groupes
paste --delimiters="$IFS" BUILD/list_photos.txt BUILD/input.csv > BUILD/global_list_1.csv


# tri par groupe
#echo "IFS=$IFS"
sort -t "$IFS" -k2,3 BUILD/global_list_1.csv >BUILD/global_list_2.csv

if [ ! -f BUILD/global_list_2.csv ]; then
	echo " -Erreur: fichier intermédiaire BUILD/global_list_2.csv absent..."
	exit 5
fi

# Génération du .tex
if [ ! -f "$header_file" ];
	then
	if [ ! -f "/etc/trombino/$header_file" ]; then
	    echo " -Erreur d'installation: fichier d'en-tête introuvable"
	    exit 5
	else
		header_file=/etc/trombino/$header_file
		echo " -Utilisation de l'en-tete par défaut $header_file"
	fi
else
	echo " -!!! Utilisation du fichier d'en tête local !!!"
fi

# Génération trombi global
outfile_tex=$outfile2
outfile_html=$outfile2_html
reset_all
process_header 0
while read line; do
#     echo "line : $line"
	process_line_all $line
done < BUILD/global_list_1.csv
close_source

if [ $latex = 1 ]
then
	outfile_tex=${out_fn}_global
	latex_build
fi


# Génération trombi par groupe
echo " Génération trombi par groupe"

declare -A groupsize
countgrsize BUILD/global_list_2.csv
reset_all
current_group=nogroup
outfile_tex=$outfile1
outfile_html=$outfile1_html
process_header 1
while read line; do
#     echo "line : $line"
	process_line $line
done < BUILD/global_list_2.csv
close_source

if [ $latex = 1 ]
then
	outfile_tex=${out_fn}_groupes
	latex_build
fi

if [ $html = 1 ]
then
	echo "</body></html>" >>$outfile_html
	cp BUILD/*.html .
fi

exit 0


# ----------------------------------------------------------------------------


